version: '3.8'

services:
  nestjs:
    build: .
    container_name: nestjs_app
    restart: always
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres  # 👈 Aquí debe ir el nombre del servicio de MySQL
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: restaurante_db
    ports:
      - "3000:3000"